name: Quality Checks
on:
  pull_request:
    branches:
      - main

jobs:
  Find-GitSHA:
    name: find Git Sha
    runs-on: ubuntu-latest
    steps:
    - name: Print commit ID
      run: echo "Commit ID - $GITHUB_SHA "

    - name: Extract repository information
      run: |
        REPO_INFO=$GITHUB_REPOSITORY
        echo "REPO_INFO: $REPO_INFO"
        OWNER=$(echo $REPO_INFO | cut -d'/' -f1)
        REPO=$(echo $REPO_INFO | cut -d'/' -f2)
        echo "Repository: $REPO"
        echo "Owner: $OWNER"

    - name: Extract commit ID and repository information
      run: |
        COMMIT_ID=$GITHUB_SHA
        REPO_INFO=$GITHUB_REPOSITORY
        echo "REPO_INFO: $REPO_INFO"
        OWNER=$(echo $REPO_INFO | cut -d'/' -f1)
        REPO=$(echo $REPO_INFO | cut -d'/' -f2)
        echo "Commit ID: $COMMIT_ID"
        echo "Repository: $REPO"
        echo "Owner: $OWNER"

    - name: Create commit status
      run: |
        API_HOST=https://api.github.com
        OWNER=$(echo $GITHUB_REPOSITORY | cut -d'/' -f1)
        REPO=$(echo $GITHUB_REPOSITORY | cut -d'/' -f2)
        REF=$GITHUB_SHA
        STATUS_URL=$API_HOST/repos/$OWNER/$REPO/statuses/$REF
        echo "STATUS_URL: $STATUS_URL"
        curl -X POST $STATUS_URL \
          -H "Authorization: Bearer $GITHUB_TOKEN" \
          -H "Content-Type: application/json" \
          -d '{
            "state": "success",
            "description": "The build was successful.",
            "context": "ci/smartui-github-testing"
          }'